packageinstaller: fix force closes when tapping notification
PackageInstaller: Fix FC when tapping on a downloaded apk notification
java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/my_downloads/831 from pid=25212, uid=10019 requires android.permission.INTERNET, or grantUriPermission()

and

PackageInstaller: Fix FC when tapping on a downloaded apk notification 2
11-24 05:30:39.780 E/AndroidRuntime(11820): FATAL EXCEPTION: AsyncTask #1
11-24 05:30:39.780 E/AndroidRuntime(11820): Process: com.android.packageinstaller, PID: 11820
11-24 05:30:39.780 E/AndroidRuntime(11820): java.lang.RuntimeException: An error occurred while executing doInBackground()
11-24 05:30:39.780 E/AndroidRuntime(11820): at android.os.AsyncTask.done(AsyncTask.java:318)
11-24 05:30:39.780 E/AndroidRuntime(11820): at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
11-24 05:30:39.780 E/AndroidRuntime(11820): at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
11-24 05:30:39.780 E/AndroidRuntime(11820): at java.util.concurrent.FutureTask.run(FutureTask.java:242)
11-24 05:30:39.780 E/AndroidRuntime(11820): at android.os.AsyncTask.run(AsyncTask.java:243)
11-24 05:30:39.780 E/AndroidRuntime(11820): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-24 05:30:39.780 E/AndroidRuntime(11820): at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:607)
11-24 05:30:39.780 E/AndroidRuntime(11820): at java.lang.Thread.run(Thread.java:761)
11-24 05:30:39.780 E/AndroidRuntime(11820): Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/101 from pid=11820, uid=10025 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()

Change-Id: I9ab5dee40796769cfabfd10ed18889518be3681d
Signed-off-by: PMS22 <prathams99@rediff.com>